apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:,-a%20always%2Cexit%20-F%20arch=b64%20-S%20clock_settime%20-F%20a0=0x0%20-k%20time-change%0A-a%20always%2Cexit%20-F%20arch=b32%20-S%20clock_settime%20-F%20a0=0x0%20-k%20time-change%0A
          mode: 384
          overwrite: true
          path: /etc/audit/rules.d/75-syscall-clock-settime.rules
