source "https://rubygems.org"

# Use older Jekyll version compatible with Ruby 2.6
gem "jekyll", "~> 4.2.0"
gem "webrick", "~> 1.7"

# Avoid ffi issues with older Ruby
gem "ffi", "< 1.16"

group :jekyll_plugins do
  gem "jekyll-relative-links"
  gem "jekyll-seo-tag"
end
